
package project.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentralLogicImplService", targetNamespace = "http://ws.project/", wsdlLocation = "https://sdeproject-musicdb.herokuapp.com/centrallogic?wsdl")
public class CentralLogicImplService
    extends Service
{

    private final static URL CENTRALLOGICIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTRALLOGICIMPLSERVICE_EXCEPTION;
    private final static QName CENTRALLOGICIMPLSERVICE_QNAME = new QName("http://ws.project/", "CentralLogicImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://sdeproject-musicdb.herokuapp.com/centrallogic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALLOGICIMPLSERVICE_WSDL_LOCATION = url;
        CENTRALLOGICIMPLSERVICE_EXCEPTION = e;
    }

    public CentralLogicImplService() {
        super(__getWsdlLocation(), CENTRALLOGICIMPLSERVICE_QNAME);
    }

    public CentralLogicImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALLOGICIMPLSERVICE_QNAME, features);
    }

    public CentralLogicImplService(URL wsdlLocation) {
        super(wsdlLocation, CENTRALLOGICIMPLSERVICE_QNAME);
    }

    public CentralLogicImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALLOGICIMPLSERVICE_QNAME, features);
    }

    public CentralLogicImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralLogicImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentralLogic
     */
    @WebEndpoint(name = "CentralLogicImplPort")
    public CentralLogic getCentralLogicImplPort() {
        return super.getPort(new QName("http://ws.project/", "CentralLogicImplPort"), CentralLogic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentralLogic
     */
    @WebEndpoint(name = "CentralLogicImplPort")
    public CentralLogic getCentralLogicImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.project/", "CentralLogicImplPort"), CentralLogic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALLOGICIMPLSERVICE_EXCEPTION!= null) {
            throw CENTRALLOGICIMPLSERVICE_EXCEPTION;
        }
        return CENTRALLOGICIMPLSERVICE_WSDL_LOCATION;
    }

}
