
package recombee.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecombeeService", targetNamespace = "http://ws.recombee/", wsdlLocation = "https://recombee-games.herokuapp.com/recombee?wsdl")
public class RecombeeService
    extends Service
{

    private final static URL RECOMBEESERVICE_WSDL_LOCATION;
    private final static WebServiceException RECOMBEESERVICE_EXCEPTION;
    private final static QName RECOMBEESERVICE_QNAME = new QName("http://ws.recombee/", "RecombeeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://recombee-games.herokuapp.com/recombee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECOMBEESERVICE_WSDL_LOCATION = url;
        RECOMBEESERVICE_EXCEPTION = e;
    }

    public RecombeeService() {
        super(__getWsdlLocation(), RECOMBEESERVICE_QNAME);
    }

    public RecombeeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECOMBEESERVICE_QNAME, features);
    }

    public RecombeeService(URL wsdlLocation) {
        super(wsdlLocation, RECOMBEESERVICE_QNAME);
    }

    public RecombeeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECOMBEESERVICE_QNAME, features);
    }

    public RecombeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecombeeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Recombee
     */
    @WebEndpoint(name = "RecombeeImplPort")
    public Recombee getRecombeeImplPort() {
        return super.getPort(new QName("http://ws.recombee/", "RecombeeImplPort"), Recombee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Recombee
     */
    @WebEndpoint(name = "RecombeeImplPort")
    public Recombee getRecombeeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.recombee/", "RecombeeImplPort"), Recombee.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECOMBEESERVICE_EXCEPTION!= null) {
            throw RECOMBEESERVICE_EXCEPTION;
        }
        return RECOMBEESERVICE_WSDL_LOCATION;
    }

}
